Add option to customize Jira priorities (#1637)
* Add option to parametries custom Jira priorities

* Build and push image to my own ghcr repo

* Update Jira documentation

* Revert "Build and push image to my own ghcr repo"

This reverts commit 2765a877dc51932294e4b4f2b93c17503680b5c5.

* Put back changed before autofmt

* Fallback to using priority id when priority is not found

* Revert "Revert "Build and push image to my own ghcr repo""

This reverts commit 6c8d2b1904f60facb337b95b7b5f31eee495642a.

* Correct fallback mechanism for  priority IDs

* Add constants for jira integration

* Correct FindingSeverity import

* Correct HTTP method parameter in Jira API calls

Fix TypeError in process_request() where method parameter was being passed
twice - once as positional argument and once in kwargs. Standardize to
use positional argument only.

Error: "process_request() got multiple values for argument 'method'"

* Use HttpMethod enum instead of string in Jira API calls

* Correct jira add attachments method

* Fix json structure for payload

* Return back url and endpoint for def create_issue

* Fix priority handling cascade with fallback logic

* Remove specific if condition for HttpMethod code and text

* Use more generate approach Exception

* Make sure _call_jira_api returns HTTPError

* Revert back auto fmt apply

* Correct indentations for create_issue comment

* Create _resolve_priority method

* Put back else clause in manage_issue method

* Add a test call to validate common priority

* Correct _resolve_priority method comment

* Revert "Revert "Revert "Build and push image to my own ghcr repo"""

This reverts commit 31f3d590dc9b365e48ab0aa76328dbafccd6c118.

* Simplify Jira priority name mapping

* Only validate priorities when logging level is DEBUG

* Fallback to creating Jira issues without priority if setting priority fails

When creating a Jira issue, if setting the priority fails, retry without
setting the priority.

* Revert to handle only two cases: used defined and default priority names

* Remove _create_issue_payload and _handle_attachment_and_return methods

* Revert to return None when Jira API error occurs